import { faker } from "@faker-js/faker";
import axios from "axios";

export const createBatchRun = async (token: string): Promise<any> => {
  const data = JSON.stringify({
    data: {
      BatchRun: {
        ID: faker.name.fullName(),
        BatchTemplateID: "",
        RequestedStartTime: "2024-01-10",
        RequestedEndTime: "2024-01-25",
        MaterialDefinition: {
          MaterialDefinitionID: "3000181",
          Quantity: "6.000 ",
          UnitOfMeasure: "EA",
          LotID: faker.name.fullName(),
        },
        BillOfMaterials: [
          {
            MaterialDefinitionID: "2000171",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000951",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000952",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000488",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000107",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000074",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001164",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000981",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001123",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000018",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000535",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000019",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000520",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000117",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000367",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000953",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          // {
          //   MaterialDefinitionID: "1000103",
          //   OperationID: "0021",
          //   BillOfMaterialsItemNumber: "1016",
          //   MaterialLotID: null,
          //   MaterialSublot: {
          //     MaterialSublotID: null,
          //     Quantity: "4.000 ",
          //     UnitOfMeasure: "EA",
          //   },
          // },
          {
            MaterialDefinitionID: "1000532",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1017",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001168",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1018",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001167",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1019",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001166",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1020",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001165",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1021",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001169",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1022",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000036",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1023",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "13.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000636",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1024",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000541",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1025",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000493",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1026",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000712",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1027",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "18.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000711",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1028",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000565",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1029",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "BX",
            },
          },
          {
            MaterialDefinitionID: "1000655",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1030",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000345",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1031",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "7.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001191",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1032",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1001177",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1033",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "7.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000779",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1034",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001228",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1035",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001230",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1036",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001229",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1037",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001210",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1038",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000799",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1039",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001038",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1040",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000105",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1041",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000584",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1042",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "13.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1043",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000121",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1044",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000557",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1045",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000023",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1046",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000707",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1047",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1048",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "5.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1000672",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1049",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000355",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1050",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000666",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1051",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000808",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1052",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000475",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1053",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1054",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0021",
            BillOfMaterialsItemNumber: "1055",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          // {
          //   MaterialDefinitionID: "1000462",
          //   OperationID: "0021",
          //   BillOfMaterialsItemNumber: "1056",
          //   MaterialLotID: null,
          //   MaterialSublot: {
          //     MaterialSublotID: null,
          //     Quantity: "3.000 ",
          //     UnitOfMeasure: "CV",
          //   },
          // },
          {
            MaterialDefinitionID: "3000191",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "17.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000780",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001258",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "20.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "4000234",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000074",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001164",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001174",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001171",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000105",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "4000255",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001226",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000121",
            OperationID: "0022",
            BillOfMaterialsItemNumber: "2015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1001166",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001169",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001168",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000023",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000707",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000107",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000121",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000655",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1000036",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "10.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001210",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000541",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000636",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000712",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "5.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001177",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "11.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000779",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000475",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3016",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000711",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3017",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000565",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3018",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "BX",
            },
          },
          {
            MaterialDefinitionID: "1000808",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3019",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          // {
          //   MaterialDefinitionID: "1000544",
          //   OperationID: "0023",
          //   BillOfMaterialsItemNumber: "3020",
          //   MaterialLotID: null,
          //   MaterialSublot: {
          //     MaterialSublotID: null,
          //     Quantity: "0.000 ",
          //     UnitOfMeasure: "PAC",
          //   },
          // },
          {
            MaterialDefinitionID: "1000355",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3021",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000666",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3022",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000489",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3023",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3024",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3025",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0023",
            BillOfMaterialsItemNumber: "3026",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1001168",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001166",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001169",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000023",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000707",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000107",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000036",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1001210",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001177",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "10.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000779",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000541",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000493",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000475",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000355",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000666",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4016",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000711",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4017",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000565",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4018",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "BX",
            },
          },
          {
            MaterialDefinitionID: "1000808",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4019",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          // {
          //   MaterialDefinitionID: "1000544",
          //   OperationID: "0024",
          //   BillOfMaterialsItemNumber: "4020",
          //   MaterialLotID: null,
          //   MaterialSublot: {
          //     MaterialSublotID: null,
          //     Quantity: "0.000 ",
          //     UnitOfMeasure: "PAC",
          //   },
          // },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4021",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4022",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000655",
            OperationID: "0024",
            BillOfMaterialsItemNumber: "4023",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1001168",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001166",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001169",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000023",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000707",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000107",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000036",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000541",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000493",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1001210",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001177",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "11.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000779",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000475",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000355",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000666",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5016",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000711",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5017",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000565",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5018",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "BX",
            },
          },
          {
            MaterialDefinitionID: "1000808",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5019",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          // {
          //   MaterialDefinitionID: "1000544",
          //   OperationID: "0025",
          //   BillOfMaterialsItemNumber: "5020",
          //   MaterialLotID: null,
          //   MaterialSublot: {
          //     MaterialSublotID: null,
          //     Quantity: "0.000 ",
          //     UnitOfMeasure: "PAC",
          //   },
          // },
          {
            MaterialDefinitionID: "1000655",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5021",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5022",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0025",
            BillOfMaterialsItemNumber: "5023",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000370",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6000",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000541",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6001",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000493",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6002",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000666",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6003",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000952",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6004",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001217",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6005",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "7.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000490",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6006",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1000034",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6007",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000355",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6008",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000036",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6009",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "30.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000537",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6010",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "BAG",
            },
          },
          {
            MaterialDefinitionID: "1001247",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6011",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "7.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000636",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6012",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000712",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6013",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "17.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000711",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6014",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000565",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6015",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "BX",
            },
          },
          {
            MaterialDefinitionID: "1000655",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6016",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000672",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6017",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001237",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6018",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "4.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001191",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6019",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000813",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6020",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000816",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6021",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000121",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6022",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000799",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6023",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001038",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6024",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1001038",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6025",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000469",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6026",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000584",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6027",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "9.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000954",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6028",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "2.000 ",
              UnitOfMeasure: "EA",
            },
          },
          {
            MaterialDefinitionID: "1000502",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6029",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "3.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000847",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6030",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "0.000 ",
              UnitOfMeasure: "PAC",
            },
          },
          {
            MaterialDefinitionID: "1000557",
            OperationID: "0026",
            BillOfMaterialsItemNumber: "6031",
            MaterialLotID: null,
            MaterialSublot: {
              MaterialSublotID: null,
              Quantity: "1.000 ",
              UnitOfMeasure: "EA",
            },
          },
        ],
        Location: {
          SiteID: "1721",
          BuildingID: "1721",
          AreaID: "2000",
          UnitID: "PAST",
        },
      },
    },
  });

  const config = {
    method: "post",
    maxBodyLength: Infinity,
    url: "http://localhost:4000/rest/BatchRuns",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    data: data,
  };

  const res = await axios.request(config);
  return res;
};
